version: "3.8"

services:
  nginx:
    build:
      context: _docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./_docker/nginx/.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php

  php:
    build:
      context: _docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel

  mysql:
    build:
      context: _docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3316:3306"
    env_file:
      - ./_docker/mysql/.env
    volumes:
      - db_data:/var/lib/mysql

  composer:
    build:
      context: _docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build:
      context: _docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_docker/mysql/db_data
