version: "3.8"

services:
  nginx:
    build:
      context: _docker/nginx/
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./_docker/nginx/.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/furia
    depends_on:
      - php
      - pgsql

  php:
    build:
      context: _docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/furia

  pgsql:
    build:
      context: _docker/pgsql
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  deno:
    build:
      context: _docker/deno
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/var/www/furia-front
    ports:
      - "1993:1993"
      - "8000:8000"

  composer:
    build:
      context: _docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/furia

  artisan:
    build:
      context: _docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/furia
    entrypoint: ["php", "/var/www/furia/artisan"]

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_docker/pgsql/db_data