version: "3.8"

services:
  nginx:
    build:
      context: _docker/nginx/
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./_docker/nginx/.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
      - pgsql
      - deno

  php:
    build:
      context: _docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel

  pgsql:
    build:
      context: _docker/pgsql
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  deno:
    build:
      context: .
      dockerfile: ./_docker/deno/Dockerfile
    volumes:
      - ./src:/var/www/laravel
    ports:
      - "1993:1993"

  composer:
    build:
      context: _docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build:
      context: _docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_docker/pgsql/db_data